# Generated by Django 2.0.5 on 2018-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180506_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
