# Generated by Django 2.0.5 on 2018-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180507_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
